# Generated by Django 5.0.14 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About C-DAC', max_length=200)),
                ('subtitle', models.CharField(default='Dedicated to excellence in practical computer education, advanced computing research, and skills training.', max_length=300)),
                ('mission_title', models.CharField(default='Our Mission', max_length=150)),
                ('description', models.TextField(default='At the Centre for Development of Advanced Computing (C-DAC), our mission is to carry out R&D in IT, Electronics and associated areas, empowering students and professionals with high-end IT education. Whether you are looking to start a career in software development, web engineering, database administration, or advanced computing, our hands-on curriculum is designed to get you industry-ready.')),
                ('feature_1_title', models.CharField(default='🎯 Practical Learning', max_length=150)),
                ('feature_1_desc', models.TextField(default='Every course emphasizes real-world projects and coding exercises over passive lecture theory.')),
                ('feature_2_title', models.CharField(default='🏆 Authentic Certification', max_length=150)),
                ('feature_2_desc', models.TextField(default='Certificates issued by C-DAC feature unique cryptographic IDs verifiable by employers globally.')),
                ('feature_3_title', models.CharField(default='👥 Community Support', max_length=150)),
                ('feature_3_desc', models.TextField(default='Dedicated lab assistants, mentor hours, and career placement assistance for all active students.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+91 (020) 2570-4100', max_length=100)),
                ('email', models.EmailField(default='contact@cdac.in', max_length=254)),
                ('address', models.TextField(default='Gandhinagar, Gujarat, India')),
                ('working_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM', max_length=150)),
                ('map_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d471.09!2d72.6320823!3d23.1852315!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395c2b921555555d%3A0x50e94504c763b697!2sCDAC%20Computer%20Class!5e0!3m2!1sen!2sin!4v1722593000000!5m2!1sen!2sin', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Details Content',
                'verbose_name_plural': 'Contact Details Content',
            },
        ),
    ]
