# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutcontent_contactcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InquiryFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback_later', 'Callback Later'), ('converted', 'Converted')], default='contacted', max_length=30)),
                ('message', models.TextField()),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry Follow-Up',
                'verbose_name_plural': 'Inquiry Follow-Ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
