# Generated by Django 5.0.14 on 2026-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aboutcontent_id_alter_contactcontent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontent',
            name='whatsapp_number',
            field=models.CharField(default='919876543210', help_text='WhatsApp number with country code (e.g. 919876543210)', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inquiryfollowup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
