# Generated by Django 5.0.14 on 2026-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactcontent_whatsapp_number_alter_aboutcontent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontent',
            name='whatsapp_auto_message',
            field=models.TextField(blank=True, default='Hello, I am interested in your courses and would like to contact the admin.', help_text='Automatic pre-filled message when user taps WhatsApp button'),
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='whatsapp_auto_message_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the automatic pre-filled message'),
        ),
    ]
