# Generated by Django 5.0.14 on 2026-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactcontent_whatsapp_auto_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcontent',
            name='whatsapp_auto_message',
        ),
        migrations.RemoveField(
            model_name='contactcontent',
            name='whatsapp_auto_message_enabled',
        ),
    ]
