# Generated by Django 5.0.14 on 2026-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_first_name_certificate_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
