# Generated by Django 5.0.14 on 2026-08-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_id'),
        ('courses', '0003_courseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
