# Generated by Django 5.0.14 on 2026-08-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short offer title for ticker, e.g., 30% OFF on Python Course', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of offer', null=True)),
                ('discount', models.CharField(blank=True, help_text='e.g., 30% OFF, ₹999 Only, Free Certificate', max_length=100, null=True)),
                ('badge', models.CharField(default='🎉 SPECIAL OFFER', help_text='Ticker badge icon/text', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='Start date for offer schedule', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for offer expiry', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority offers appear first in ticker')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Offer',
                'verbose_name_plural': 'Course Offers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
