# Generated by Django 6.0.6 on 2026-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('accounting', 'Accounting'), ('programming', 'Programming'), ('diploma-6-months', 'Diploma (6 Months)'), ('advance-diploma-12-months', 'Advance Diploma (12 Months)'), ('frontend-full-stack-development', 'Frontend / Full Stack Development'), ('modular-courses', 'Modular Courses')], default='basic', help_text='Select the main Course Category', max_length=100),
        ),
    ]
